### ISSUE TITLE
Practice Lab 4 Incident type - missing "taxable" field from form

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-240-Dynamics365forFieldService#58] opened 2023-04-04 14:39 UTC
# Practice Lab: 04
#### Step: 05

Description of issue
* there is no taxable field on the form.
* 
![image](https://user-images.githubusercontent.com/89986870/229827895-fc1c9598-c9fe-415d-8b33-6200ac39e588.png)

#### Step: 05

Description of issue
* there is no taxable field on the form.

![image](https://user-images.githubusercontent.com/89986870/229832147-20744e9e-1517-4f9d-8cb2-aa38757a94a6.png)

**Comment by ephiax20** [comment] 2023-06-30 13:19
@chaast Similar to #57 I'm not able to replicate this.   I am seeing the Taxable field. Waiting to hear back from the ALH on this.

![image](https://github.com/MicrosoftLearning/MB-240-Dynamics365forFieldService/assets/116392278/e14bf8e2-952a-49dd-9220-b4bc46833ab1)

![image](https://github.com/MicrosoftLearning/MB-240-Dynamics365forFieldService/assets/116392278/9505e1ad-d795-4a05-9102-179cfe259b0f)

**Comment by ephiax20** [comment] 2023-07-05 14:17
Closing this, as a duplicate of #57

**Closed as completed by ephiax20** 2023-07-05 14:17 UTC
